module PSN
  class Client
    def initialize: (?npsso: String?, ?refresh_token: String?, ?language: String,
                     ?on_token_refresh: Auth::token_refresh_callback?) -> void
    def games: () -> Resources::Games
    def trophies: () -> Resources::Trophies
    def store: () -> Resources::Store
    def profiles: () -> Resources::Profiles
    def search: () -> Resources::Search
    def catalog: () -> Resources::Catalog
    def social: () -> Resources::Social
    def devices: () -> Resources::Devices
    def media: () -> Resources::Media
    def groups: () -> Resources::Groups
    def browse: () -> Resources::Browse
    def access_token: () -> String
    def refresh_token: () -> String?
    def access_token_expires_at: () -> Time?

    private

    def users: () -> Resources::Users
  end
end
